name: Build

on:
  push:
    branches:
      - dev
      - release
      - prerelease
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yml'
  pull_request:
    branches:
      - dev
      - release
      - prerelease
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        sln:
          - Spriggit.sln
          - Spriggit.Linux.sln
        exclude:
          - os: ubuntu-latest
            sln: Spriggit.sln
          - os: ubuntu-latest
            sln: Spriggit.Tests.Windows.sln
          - os: macos-latest
            sln: Spriggit.sln
          - os: macos-latest
            sln: Spriggit.Tests.Windows.sln
          - os: windows-latest
            sln: Spriggit.Linux.sln
          
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.*
    - name: Install dependencies
      run: |
        dotnet clean ${{ matrix.sln }} -c Release && dotnet nuget locals all --clear
        dotnet restore ${{ matrix.sln }}
    - name: Build
      run: dotnet build ${{ matrix.sln }} -c Release --no-restore /p:GeneratePackageOnBuild=false
    - name: Test
      run: dotnet test ${{ matrix.sln }} -c Release --no-build
