name: Publish

on:
  schedule:
    - cron: '40 9 * * *'
  workflow_dispatch:
  release:
    types: [published]
    inputs:
      is_release_event:
        description: Should this be a release or a preview package
        required: true
        default: 'false'

jobs:
  activity-short-circuit:
    runs-on: ubuntu-latest
    outputs:
      same_sha: ${{ steps.check.outputs.same_sha }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Get Activity Short Circuit
        id: check
        run: |
          git branch -a
          git fetch origin nightly:nightly
          head_sha=$(git rev-parse --verify HEAD)
          nightly_sha=$(git rev-parse --verify nightly)
          if [[ "$head_sha" == "$nightly_sha" ]]; then
              same_sha=true;
          else
              same_sha=false;
          fi
          echo "head_sha=$head_sha"
          echo "nightly_sha=$nightly_sha"
          echo "same_sha=${same_sha}"
          echo "same_sha=${same_sha}" >> $GITHUB_OUTPUT
        
  build-test:
    needs: activity-short-circuit
    if: needs.activity-short-circuit.outputs.same_sha == 'false'
    runs-on: windows-latest
          
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        dotnet clean -c Release && dotnet nuget locals all --clear
        dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test -c Release --no-build


  build-test-push:
    needs: [build-test, activity-short-circuit]
    if: needs.activity-short-circuit.outputs.same_sha == 'false'
    runs-on: windows-latest
    steps:
    - name: Get timestamp
      uses: 1466587594/get-current-time@v1
      id: current-time
      with:
        format: YYYYMMDD-HHmmSS
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install dependencies
      run: |
        dotnet clean -c Release && dotnet nuget locals all --clear
        dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore /p:GeneratePackageOnBuild=false
    - name: Pack Preview
      if: ${{ success() && (github.event.inputs.is_release_event != 'true' || github.ref != 'refs/heads/release') }}
      run: |
        dotnet pack -c Release --no-build --no-restore -o out --version-suffix "nightly-${{ steps.current-time.outputs.formattedTime }}"
    - name: Pack Release
      if: ${{ success() && github.event.inputs.is_release_event == 'true' && github.ref == 'refs/heads/release' }}
      run: | 
        dotnet pack -c Release --no-build --no-restore -o out
  
  update-nightly:
    needs: [build-test-push, activity-short-circuit]
    if: needs.activity-short-circuit.outputs.same_sha == 'false'
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Reset nightly to release
      run: |
        head_sha=$(git rev-parse --verify HEAD)
        echo "head_sha=$head_sha"
        git checkout nightly
        git reset --hard $head_sha
        git push